### ISSUE TITLE
Get Stacktrace When Trying to Register a New User

### ISSUE THREAD

**Issue by dchokola** [mrDoctorWho/lua-captcha#3]
I am using Prosody trunk nightly build 679 (2016-06-28, ced4e800f42a) and I get the following error when trying to register a new user:

`Jul 02 13:54:43 c2s24e65f0      error   Traceback[c2s]: /usr/local/lib/lua/5.1/captcha.lua:158: bad argument #2 to 'jpeg' (number expected, got nil)
stack traceback:
        [C]: in function 'jpeg'
        /usr/local/lib/lua/5.1/captcha.lua:158: in function 'jpeg'
        /usr/local/lib/lua/5.1/captcha.lua:186: in function 'write'
        /usr/lib/prosody/modules/mod_register.lua:229: in function 'get_captcha'
        /usr/lib/prosody/modules/mod_register.lua:246: in function '?'
        /usr/lib/prosody/util/events.lua:78: in function </usr/lib/prosody/util/events.lua:74>
        (tail call): ?
        /usr/lib/prosody/core/stanza_router.lua:148: in function 'core_process_stanza'
        /usr/lib/prosody/modules/mod_c2s.lua:247: in function 'func'
        /usr/lib/prosody/util/async.lua:90: in function </usr/lib/prosody/util/async.lua:88>`

**Comment by dchokola** [comment]
I changed mod_regisiter.lua:229 from:
`captcha_ids[cid] = cap:write(string.format("%s/%s.png", config.dir, cid)):lower();`
to:
`captcha_ids[cid] = cap:write(string.format("%s/%s.png", config.dir, cid), 90):lower();`
and can now see captchas in my client.

**Comment by mrDoctorWho** [comment]
Hello and thank you for your report!

But you reported into a wrong repository. Closing for this reason.
